"use client"

import React from "react";
import CartSection from "@/src/components/Cart/CartSection.jsx";
import { Provider } from "react-redux";
import { store } from "@/src/store";

export const metadata = {
  title: "Giỏ hàng",
  // description: "Generated by create next app"
};

export default function Cart() {
  return (
    <Provider store={store}>
      <CartSection />
    </Provider>
  );
}
