import CartReduce from "@/src/components/Cart/CartReduce";
import React from "react";
export const metadata = {
  title: "Giỏ hàng"
  // description: "Generated by create next app"
};

export default function Cart() {
  return (
    <>
      <CartReduce />
    </>
  );
}
