import Head from "@/src/components/Layout/Header";
import "@/src/styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Head />
        <main className="px-6 md:px-10">{children}</main>
      </body>
    </html>
  );
}
